package aoc

import aoc.day.Day01

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class App {

    static void main(String[] args) {
        final def DAYS = ["01": new Day01()] as HashMap<String, AoCDay>

        DAYS.each { day ->
            final def input = loadInputForDay(day.key)
            day.value.with {
                part1(input)
                part2(input)
            }
        }
    }

    private static loadInputForDay(String day) {
        try {
            getClass().getResource("/day${day}.txt").readLines()
        } catch (IOException | NullPointerException ex) {
            throw new IOException(ex)
        }
    }
}
